### ISSUE TITLE
When using listExtendQuery with groupby, paginate seems not work

### ISSUE THREAD

**Issue by fanti1** [wintercms/winter#454]
### Winter CMS Build

Other (please specify below)

### PHP Version

7.4

### Database engine

MySQL/MariaDB

### Issue description

Hello everyone.
I have a model listing, where I need to override the standard querie, using a groupBy that returns the desired results, according to the business rule. The values ​​that appear as "totals" in the pagination are correct.

The problem is, when doing this:
 public function listExtendQuery($query)
    {
     $query->groupBy('column');
    }
    
  And when trying to move from one page to another, it just doesn't load. I get stuck on the first page.
  See: the pagination widget is loaded, but it doesn't work when I click next page...
  
  Does anyone have any ideas?

### Steps to replicate

• Use any model with some data
• In the controller of above's model, use the listExtendQuery to override default querie using: $query->groupBy('some_column')
• Try to click in the next step indicator

### Workaround

Nothing yet.

**Comment by maricruztm** [comment]
Hi,
I have the same issue with a backend list. It has a groupBy as I'm joining more tables to the query, which gives me duplicated rows of the main table. This used to work in older versions (I was on OctoberCMS and migrated to WinterCMS 1.1.8).

I'm trying with distinct('main_table.id') but that breaks the items count. leaving the group by is fine but it breaks the pagination.

As far as I know, some logic has changed around pagination in Laravel from version 6 and therefore the issue?

Any workaround to fix this?

Thanks a lot

**Comment by mjauvin** [comment]
@maricruztm from what October version did you migrate from (the one where it worked) ?

**Comment by maricruztm** [comment]
I cannot double check that anymore but I think it was 448: https://github.com/octobercms/october/tree/v1.0.448

**Comment by LukeTowers** [comment]
Is this still an issue in Winter v1.2?

**Comment by maricruztm** [comment]
Hi,

We haven't done the migration yet but will do in a few weeks. Would it be
OK to leave this open until then please?

Thanks

**Comment by LukeTowers** [comment]
@maricruztm were you able to complete the migration to Winter v1.2 yet?

**Comment by fanti1** [comment]
> Is this still an issue in Winter v1.2?

Just made a test with winter 1.2.1 and this issue continues. Any idea?

**Comment by bennothommo** [comment]
@fanti1 I've just tried your replication details and I can't replicate this. There must be something else at play here. Do you have any other conditions in the query, or are using any filters?

If possible, could you try installing the [Debug Bar](https://github.com/wintercms/wn-debugbar-plugin) and provide us with a copy of the query that runs for your list (it should be the query - or queries - that runs on your model's database tables)?

**Comment by fanti1** [comment]
Hi @bennothommo. Testing with *** Detected Winter CMS build 1.2.1.
I've created an model Test with this fields:
![image](https://user-images.githubusercontent.com/23063442/204789748-77335a96-4838-4d29-ae3c-7f5487d83bbe.png)
Then, in controller I just do:
![image](https://user-images.githubusercontent.com/23063442/204789885-6751dc89-4745-448c-a6da-01cd36a35bc2.png)
When doing this, I need to set config/database.php strict to false, to solve some groupBy error, I don't understand exactly why...
I've changed at config_list the records per page to 3, to do the test easier with few records.
![image](https://user-images.githubusercontent.com/23063442/204790429-8aa25ade-c4ba-4754-8313-32a32aeaa86e.png)
And now, when I try to click next, doesn't work

**Comment by maricruztm** [comment]
Hi,

Sorry. I'm on maternity leave at the moment and I'm not sure if my team has
done it. I'll be back in a couple of months and will give you an update
then.

Thanks,
Maria

**Comment by immanolo** [comment]
Hello, 

I've encountered the same issue.

As per checking with the query logs when groupBy is used, it is also appended to the count query which I think is used by the ListController for pagination.

To replicate the issue:
 - Step1: Implement listExtendQuery on your controller:
 
```
    public function listExtendQuery($query)
    {        
        $query->groupBy('id');
    }
```

- Step2: Log the query executions:
```
\Illuminate\Support\Facades\DB::listen(function ($query) {
    // Get the executed SQL query
    $sql = $query->sql;
  
    if (str_starts_with(strtoupper(trim($sql)), 'SELECT')) {
        $bindings = $query->bindings;
        $time = $query->time;
  
        $fullSql = vsprintf(str_replace(['%', '?'], ['%%', '%s'], $sql), $bindings);
  
        Log::info("SQL Query: {$fullSql} Time: {$time}ms");
    }   
  });
```

Count query log result:
  - SQL Query: `select count(*) as aggregate from table_name group by id;`
  - Fetches the total count by group instead of one entity/row.

**Comment by lex0r** [comment]
@bennothommo @mjauvin  this issue is still very much relevant. It looks like it was abandoned due to lack of traction from the community, but I can confirm I faced it and have a fix. Will be sharing a PR for it.
